### ISSUE TITLE
Not able to burn .bin format

### ISSUE THREAD

**Issue by souviksaha97** [fahad80/stlink_utility_automation#1]
I've been facing issues burning files in .bin format. I've tried .hex format and they work well, but most of the code we generate is in .bin and we don't want to convert it back to .hex format. Is there any way I can use .bin format?

**Comment by mirzafahad** [comment]
@souviksaha97 
ST-Link Utility supports .bin files. If you check its [user manual](https://www.st.com/resource/en/user_manual/cd00262073-stm32-stlink-utility-software-description-stmicroelectronics.pdf), turn to page 38, section 4.1.3 Flash commands. It shows an example.

**Comment by souviksaha97** [comment]
Is an address necessary when programming .bin?

**Comment by mirzafahad** [comment]
@souviksaha97 Yes. If not CLI will use 0x00000000. If you are not sure what address to use you can simply check the utility software.


![Utility](https://user-images.githubusercontent.com/10793932/81497061-a8e15e80-9281-11ea-8157-a7df9aee9a56.png)

**Comment by souviksaha97** [comment]
Okay thanks, I'll close this issue.
